
build_subsets:
	#cd Data && make
	#../separarEntradas.py Data/todos_dados.fann
	@echo 'DATASETS: The sets are already created.'

clean:
	#cd Data && make clean
	#rm -f *.train ../config.pyc
	@echo 'DATASETS: The sets will not be cleaned, because we will use the same created in first time to all tests.'
